id: I8C165740
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T14:51:10.751041'
last_modified: '2022-05-27T14:51:10.751053'
parser: null
source_metadata:
  title: Brahmaśrīvyākaraṇa
  language: en
  base:
    f0738:
      title: Title
      base_file: f0738.txt
      order: 1
    f5944:
      title: Preface
      base_file: f5944.txt
      order: 2
    f6D64:
      title: Colophon
      base_file: f6D64.txt
      order: 3
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
